---
#   Copyright 2022 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

###########################################
# tasks file for job_tables
###########################################
- name: Ensure directory {{ sapopsyschk_dir_temp_managednode }} exists
  file:
    path: "{{ sapopsyschk_dir_temp_managednode }}"
    state: directory
    mode: '0755'

- name: Create a symbolic link for db2
  file:
    src: /QOpenSys/usr/bin/qsh
    dest: "{{ sapopsyschk_dir_temp_managednode }}/db2"
    state: link

- name: Check Job Tables
  shell:
    cmd: db2 "SELECT IN_USE_JOB_TABLE_ENTRIES, MAXIMUM_JOBS_IN_SYSTEM FROM QSYS2.SYSTEM_STATUS_INFO"
  args:
    chdir: "{{ sapopsyschk_dir_temp_managednode }}"
  register: sapopsyschk_job_tables_output

- name: Show Job Tables
  debug:
    msg:  "{{ sapopsyschk_job_tables_output.stdout_lines }}"

- name: Get in use Job Tables number
  shell:
    cmd: db2 "SELECT IN_USE_JOB_TABLE_ENTRIES, MAXIMUM_JOBS_IN_SYSTEM FROM QSYS2.SYSTEM_STATUS_INFO" | awk 'NR == 4 { print $1}'
  args:
    chdir: "{{ sapopsyschk_dir_temp_managednode }}"
  register: sapopsyschk_job_tables_nr_output

- name: Get max Job Tables number
  shell:
   cmd: db2 "SELECT IN_USE_JOB_TABLE_ENTRIES, MAXIMUM_JOBS_IN_SYSTEM FROM QSYS2.SYSTEM_STATUS_INFO" | awk 'NR == 4 { print $2}'
  args:
    chdir: "{{ sapopsyschk_dir_temp_managednode }}"
  register: sapopsyschk_max_job_tables_nr_output

- name: Calculate used percentage
  set_fact:
    sapopsyschk_job_tables_percent: "{{ '{:0.2f}'.format(100 * sapopsyschk_job_tables_nr_output.stdout|int / sapopsyschk_max_job_tables_nr_output.stdout|int) }}"

- name: Show Used percent
  debug:
    msg:  "OK: {{ sapopsyschk_job_tables_percent }} % used"
  when: sapopsyschk_job_tables_percent|int < sapopsyschk_job_tables_percent_input

- name: Show Used percent
  debug:
    msg:  "WARNING: {{ sapopsyschk_job_tables_percent }} % used"
  when:  sapopsyschk_job_tables_percent|int > sapopsyschk_job_tables_percent_input

- name: Ensure {{ sapopsyschk_dir_temp_managednode }} directory is removed from {{ inventory_hostname }}
  file:
    path: "{{ sapopsyschk_dir_temp_managednode }}"
    state: absent
    mode: '0755'
