---
#   Copyright 2021 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#  when:  release_switch: True

###########################################
# Prepare target work dir and ILE libary
############################################

- name: Create work directory {{ kernel_upgrade_work_dir }}
  file:
    path: "{{ kernel_upgrade_work_dir }}"
    state: directory
    
- name: Check the ILE library
  shell:
    cmd: "system 'CHKOBJ OBJ(SAP_TOOLS) OBJTYPE(*LIB)'|grep CPF9801|cat"
  register: sap_tool_check

- name: Create ILE library
  shell:
    cmd: "system 'CRTLIB LIB(SAP_TOOLS)'"
  when: sap_tool_check.stdout != ""

- name: Clear ILE library
  shell:
    cmd: "system 'CLRLIB LIB(SAP_TOOLS)'"
  when: sap_tool_check.stdout == ""

#########################################################
# Check SAPCAR
#########################################################
# Copy SAPCAR into working directory (e.g. /tmp/apysidkrn).
# The algorithm to search for SAPCAR is very similar to
# role install_saphostagent:
#   1) search in the directory that is given explicitly
#   2) search in the downloads directory
#   3) search in /usr/sap/hostctrl/exe

- name: Check SAPCAR in {{ kernel_download_dir }} folder
  ansible.builtin.stat:
    path: "{{ kernel_download_dir }}/{{ sap_hostagent_sapcar_file_name }}"
  register: stat_result
  when: sap_sapcar_local_path is undefined

- name: Set SAPCAR path variable
  ansible.builtin.set_fact:
    sap_sapcar_local_path: "{{ kernel_download_dir }}"
  when: ( sap_sapcar_local_path is undefined ) and ( stat_result.stat.exists == true ) and ( stat_result.stat.executable == true )


- name: Check SAPCAR in /usr/sap/hostctrl/exe folder
  ansible.builtin.stat:
    path: "{{ sap_sapcar_local_path_default }}/{{ sap_hostagent_sapcar_file_name }}"
  register: stat_result
  when: sap_sapcar_local_path is undefined

- name: Set SAPCAR path variable to default
  ansible.builtin.set_fact:
    sap_sapcar_local_path: "{{ sap_sapcar_local_path_default }}"
  when: ( sap_sapcar_local_path is undefined ) and ( stat_result.stat.exists == true ) and ( stat_result.stat.executable == true )


- name: Terminate if SAPCAR file not found
  fail:
    msg: "Error: {{ sap_hostagent_sapcar_file_name }} not found, neither in {{ kernel_download_dir }}, nor in {{ sap_sapcar_local_path_default }}"
  when: sap_sapcar_local_path is undefined
  
- name: Copy SAPCAR into Work-Directory
  copy:
    src: "{{ sap_sapcar_local_path }}/{{ sap_hostagent_sapcar_file_name }}"
    dest: "{{ kernel_upgrade_work_dir }}/"
    remote_src: yes
    
#########################################################
# Using SAPCAR to unpack the archive
#########################################################

- name: Change directory to Work Directory
  shell:
    cmd: system "CHGCURDIR DIR('{{ kernel_upgrade_work_dir }}')"

- name: Get fully qualified name of  ILE_<nnn>.SAR  or  SAPEXE_<nnn>.SAR  -->  <sar file>
  shell:
    cmd: "ls -d {{ kernel_download_dir }}/SAPEXE_*.SAR"
  register: sar_file
  
- name: Using SAPCAR to unpack the archive
  shell:
    cmd: system "CALL QP2SHELL PARM('/QOpenSys/usr/bin/csh' '-c' '{{ kernel_upgrade_work_dir }}/{{ sap_hostagent_sapcar_file_name }} -xvf {{ sar_file.stdout }} iletools ILE_TOOLS;iletools')"

- name: Determining the user concept
  stat:
    path: "/sapmnt/{{ sap_sid }}/profile/.newuserconcept"
  register: stat_result

#########################################################
# Setting the authorization of the objects in SAP_TOOLS
#########################################################
  
- name: Set CLASSICUSERCONCEPT to No
  ansible.builtin.set_fact:
    addenvar_value: N
  when: stat_result.stat.exists == True
  
- name: Set CLASSICUSERCONCEPT to Yes
  ansible.builtin.set_fact:
    addenvar_value: Y
  when: stat_result.stat.exists == False

- name: FIXSAPOWN SID(*NONE) LIB(SAP_TOOLS)
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') VALUE('N') REPLACE(*YES)
        ADDENVVAR ENVVAR(CLASSICUSERCONCEPT) VALUE('{{ addenvar_value }}') REPLACE(*YES)
        ADDLIBLE LIB(SAP_TOOLS)
        SAP_TOOLS/FIXSAPOWN SID(*NONE) LIB(SAP_TOOLS)
        EOF

#########################################################
# Upgrade Kernel
#########################################################

- name: Execute kernel upgrade through mode TESTF
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') VALUE('N') REPLACE(*YES)
        ADDENVVAR ENVVAR(CLASSICUSERCONCEPT) VALUE('{{ addenvar_value }}') REPLACE(*YES)
        ADDLIBLE LIB(SAP_TOOLS)
        SAP_TOOLS/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_testf_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*TESTF)
        EOF
  register: cmd_mode_testf

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_testf_log_{{ sap_kernel_upgrade_log_timestamp }}"
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_testf_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_testf_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == ""

- name: Display error
  debug:
    msg: "{{ cmd_mode_testf.stderr_lines }}"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_testf.stdout_lines }}"

- name: Execute kernel upgrade through mode FULLY
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') VALUE('N') REPLACE(*YES)
        ADDENVVAR ENVVAR(CLASSICUSERCONCEPT) VALUE('{{ addenvar_value }}') REPLACE(*YES)
        ADDLIBLE LIB(SAP_TOOLS)
        SAP_TOOLS/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_fully_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*FULLY)
        EOF
  register: cmd_mode_fully

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_fully_log_{{ sap_kernel_upgrade_log_timestamp }}
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_fully_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_new_fully_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == ""

- name: Display error
  debug:
    msg: "{{ cmd_mode_fully.stderr_lines }}"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_fully.stdout_lines }}"
