---
#   Copyright 2021 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#########################################################
# Upgrade Kernel
#########################################################

- name: Execute kernel upgrade through ILE mode TEST
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') +
        VALUE('N') REPLACE(*YES)
        ADDLIBLE LIB(SAP{{ sap_sid }}IND)
        SAP{{ sap_sid }}IND/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_test_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*TEST)
        EOF
  register: cmd_mode_test
  when: kernel_upgrade_mode == "ADD"

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_test_log_{{ sap_kernel_upgrade_log_timestamp }}
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_test_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log
  when: kernel_upgrade_mode == "ADD"

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_test_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == "" and kernel_upgrade_mode == "ADD"

- name: Display error
  debug:
    msg: "{{ cmd_mode_test.stderr_lines }}"
  when: kernel_upgrade_mode == "ADD"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_test.stdout_lines }}"
  when: kernel_upgrade_mode == "ADD"

- name: Execute kernel upgrade through ILE mode ADD
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') +
        VALUE('N') REPLACE(*YES)
        ADDLIBLE LIB(SAP{{ sap_sid }}IND)
        SAP{{ sap_sid }}IND/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_add_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*ADD)
        EOF
  register: cmd_mode_add
  when: kernel_upgrade_mode == "ADD"

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_add_log_{{ sap_kernel_upgrade_log_timestamp }}
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_add_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log
  when: kernel_upgrade_mode == "ADD"

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_add_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == "" and kernel_upgrade_mode == "ADD"

- name: Display error
  debug:
    msg: "{{ cmd_mode_add.stderr_lines }}"
  when: kernel_upgrade_mode == "ADD"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_add.stdout_lines }}"
  when: kernel_upgrade_mode == "ADD"
  
- name: Execute kernel upgrade through ILE mode TESTF
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') +
        VALUE('N') REPLACE(*YES)
        ADDLIBLE LIB(SAP{{ sap_sid }}IND)
        SAP{{ sap_sid }}IND/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_testf_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*TESTF)
        EOF
  register: cmd_mode_testf
  when: kernel_upgrade_mode == "FULLY"

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_testf_log_{{ sap_kernel_upgrade_log_timestamp }}
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_testf_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log
  when: kernel_upgrade_mode == "FULLY"

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_testf_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == "" and kernel_upgrade_mode == "FULLY"

- name: Display error
  debug:
    msg: "{{ cmd_mode_testf.stderr_lines }}"
  when: kernel_upgrade_mode == "FULLY"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_testf.stdout_lines }}"
  when: kernel_upgrade_mode == "FULLY"

- name: Execute kernel upgrade through ILE mode FULLY
  shell:
    cmd: |
        cat <<EOF | /bin/sh {{ kernel_upgrade_dir }}/clwrapper.sh
        MONMSG MSGID(CPF0000)
        ADDENVVAR ENVVAR('QIBM_USE_DESCRIPTOR_STDIO') +
        VALUE('N') REPLACE(*YES)
        ADDLIBLE LIB(SAP{{ sap_sid }}IND)
        SAP{{ sap_sid }}IND/APYSIDKRN SID({{ sap_sid }}) +
        ARCHIVES('{{ kernel_download_dir }}/*') +
        LOGPATH('/sapmnt/{{ sap_sid }}/patches/log/krnl_upg_fully_log_{{ sap_kernel_upgrade_log_timestamp }}') +
        MODE(*FULLY)
        EOF
  register: cmd_mode_add
  when: kernel_upgrade_mode == "FULLY"

- name: Check Success in LOG /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_fully_log_{{ sap_kernel_upgrade_log_timestamp }}
  shell: "grep 'Process finished successfully' /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_fully_log_{{ sap_kernel_upgrade_log_timestamp }}"
  register: check_log
  when: kernel_upgrade_mode == "FULLY"

- name: No Success in LOG
  fail:
    msg: "Error: Please check the LOG: /sapmnt/{{ sap_sid }}/patches/log/krnl_upg_fully_log_{{ sap_kernel_upgrade_log_timestamp }}"
  when: check_log == "" and kernel_upgrade_mode == "FULLY"

- name: Display error
  debug:
    msg: "{{ cmd_mode_add.stderr_lines }}"
  when: kernel_upgrade_mode == "FULLY"

- name: Display Output
  debug:
    msg: "{{ cmd_mode_add.stdout_lines }}"
  when: kernel_upgrade_mode == "FULLY"
